backend:
  name: github
  repo: alexgdesigner-dev/brutalgrafika
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "_proyectos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titulo", name: "title", widget: "string" }
      - label: "Categoria"
        name: "categoria"
        widget: "select"
        options:
          - { label: "Poster
