backend:
  name: github
  repo: alexgdesigner-dev/brutalgrafika
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "portfolio"
    label: "Portfolio"
    folder: "_proyectos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titulo", name: "title", widget: "string" }
      - label: "Categoria"
        name: "categoria"
        widget: "select"
        options:
          - { label: "Poster", value: "poster" }
          - { label: "Vinilo", value: "vinilo" }
          - { label: "Branding", value: "branding" }
          - { label: "Web", value: "web" }
      - { label: "Imagen", name: "imagen", widget: "image" }
      - { label: "Descripcion", name: "descripcion", widget: "string", required: false }
      - { label: "Ciudad", name: "ciudad", widget: "string", default: "CDMX" }
      - { label: "Anio", name: "anio", widget: "string", default: "2026" }
